# Generated by Django 6.1.1 on 2026-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='Activity',
            field=models.BooleanField(default=True),
        ),
    ]
